import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { promisify } from "node:util";

const run = promisify(execFile);

test("dashboard preview is generated by the Rust preview command", async () => {
  await run(process.execPath, ["scripts/capture-preview.mjs"]);
  const svg = await readFile("docs/dashboard-preview.svg", "utf8");

  assert.match(svg, /^<svg xmlns=/);
  assert.match(svg, /width="340" height="422"/);
  assert.match(svg, /Herdr Quota/);
  assert.match(svg, /Rows 1–17 of 17/);
  assert.match(svg, /Code review[^<]+· not reported/);
  assert.match(svg, /xml:space="preserve"/);
});
