import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { promisify } from "node:util";

const run = promisify(execFile);

test("dashboard preview is generated by the Rust preview command", async () => {
  await run(process.execPath, ["scripts/capture-preview.mjs"]);
  const svg = await readFile("docs/dashboard-preview.svg", "utf8");

  assert.match(svg, /^<svg xmlns=/);
  assert.match(svg, /width="340" height="224"/);
  assert.match(svg, /Herdr Quota/);
  assert.match(svg, /Quota remaining/);
  assert.match(svg, /role="img" aria-labelledby="title description"/);
  assert.match(svg, /Readable provider names/);
  assert.match(svg, /&gt;Claude/);
  assert.match(svg, /Week[^<]+▍────[^<]+9%/);
  assert.match(svg, /↻5d0h/);
  assert.match(svg, /Codex/);
  assert.match(svg, /Week[^<]+███▉─[^<]+79%/);
  assert.match(svg, /! Claude: out/);
  assert.match(svg, /enter info/);
  assert.doesNotMatch(svg, /Rows |Account 1|starburst|reset unavailable/);
  assert.doesNotMatch(svg, /Users|home|auth\.json|source|plan|Bearer/i);
  assert.match(svg, /xml:space="preserve"/);
});
