import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { promisify } from "node:util";

const run = promisify(execFile);

test("dashboard preview is generated by the Rust preview command", async () => {
  await run(process.execPath, ["scripts/capture-preview.mjs"]);
  const svg = await readFile("docs/dashboard-preview.svg", "utf8");

  assert.match(svg, /^<svg xmlns=/);
  assert.match(svg, /width="340" height="224"/);
  assert.match(svg, /Herdr Quota/);
  assert.match(svg, /4 ready · 2 sign-in/);
  assert.match(svg, /role="img" aria-labelledby="title description"/);
  assert.match(svg, /Provider marks: starburst Claude/);
  assert.match(svg, /&gt;✳ {2}Claude/);
  assert.match(svg, /&gt; Account 1/);
  assert.match(svg, /Week[^<]+▋─────── 9%/);
  assert.match(svg, /reset 09\/08 12:00 · in 5d 0h/);
  assert.match(svg, /⌬ {2}Codex/);
  assert.match(svg, /Week[^<]+██████▎─ 79%/);
  assert.match(svg, /! out [^<]+/);
  assert.match(svg, /enter details/);
  assert.doesNotMatch(svg, /Rows /);
  assert.doesNotMatch(svg, /3rd-party/);
  assert.doesNotMatch(svg, /Users|home|auth\.json|source|plan|Bearer/i);
  assert.match(svg, /xml:space="preserve"/);
});
